### ISSUE TITLE
Doesn't work on Python project with `src` layout

### ISSUE THREAD

**Issue by debakarr** [gabotechs/dep-tree#70]
Take for example https://github.com/pyca/cryptography

I tried [dep-tree-explorer](https://dep-tree-explorer.vercel.app/) with the following input:

- GitHub Project: https://github.com/pyca/cryptography
- Entrypoint: src/cryptography/__init__.py

![image](https://github.com/gabotechs/dep-tree/assets/17507690/8912bd1d-e1a5-4e23-9b8f-8816f546373d)

**Comment by gabotechs** [comment]
That happens because absolute imports are resolved from the root of the project, and the code is nested under `src`, but absolute imports in that codebase assume that there's no `src` folder.

You can overcome this using the environment variable PYTHONPATH like this:
```
export PYTHONPATH=src
```
and dep-tree will also resolve absolute imports that live in the `src` folder
